hawkular_server:
  url: http://127.0.0.1:8080
  tenant: hawkular
  credentials:
    username: jdoe
    password: password
emitter:
  address: :8081
  status_enabled: true
  status_credentials:
    username: dev
    password: changeme
collector:
  minimum_collection_interval: 10s
  tags:
    namespace_id: ${POD:namespace_uid}
    namespace_name: ${POD:namespace_name}
    node_name: ${POD:node_name}
    pod_id: ${POD:uid}
    pod_name: ${POD:name}
    pod_namespace: ${POD:namespace_name}
    hostname: ${POD:hostname}
    subdomain: ${POD:subdomain}
    labels: ${POD:labels}
kubernetes:
  master_url: https://10.2.2.2:8443
  #ca_cert_file: /path/to/ca.crt
  #token: ...bearer token here...
  #pod_name: hawkular-metrics-ns2ij
  #pod_namespace: openshift-infra
endpoints:
  - type: prometheus
    enabled: false
    url: http://127.0.0.1:8081/metrics
    collection_interval: 1m
    metrics:
    - name: hawkular_openshift_agent_metric_data_points_collected_total
    - name: hawkular_openshift_agent_monitored_pods
    - name: hawkular_openshift_agent_monitored_endpoints
    - name: go_goroutines
    - name: process_resident_memory_bytes
    - name: process_virtual_memory_bytes
