id: hawkular-openshift-agent-example-prometheus-python
kind: Template
apiVersion: v1
name: hawkular-openshift-agent-example-prometheus-python
metadata:
  name: hawkular-openshift-agent-example-prometheus-python
  labels:
    hawkular-openshift-agent-example: prometheus-python
parameters:
- description: The version of the image to use
  name: IMAGE_VERSION
  value: latest
objects:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: hawkular-openshift-agent-example-prometheus-python
    labels:
      name: hawkular-openshift-agent-example-prometheus-python
      hawkular-openshift-agent-example: prometheus-python
  spec:
    selector:
      name: hawkular-openshift-agent-example-prometheus-python
    replicas: 1
    template:
      version: v1
      metadata:
        labels:
          name: hawkular-openshift-agent-example-prometheus-python
          hawkular-openshift-agent-example: prometheus-python
      spec:
        containers:
        - image: hawkular/hawkular-openshift-agent-example-prometheus-python:${IMAGE_VERSION}
          name: hawkular-openshift-agent-example-prometheus-python
        volumes:
        - name: hawkular-openshift-agent
          configMap:
            name: hawkular-openshift-agent-example-prometheus-python
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: hawkular-openshift-agent-example-prometheus-python
    labels:
      name: hawkular-openshift-agent-example-prometheus-python
      hawkular-openshift-agent-example: prometheus-python
  data:
    hawkular-openshift-agent: |
      endpoints:
      - type: prometheus
        protocol: "http"
        port: 8181
        path: /
        collection_interval: 30s
        metrics:
        - name: process_virtual_memory_bytes
          type: gauge
        - name: process_resident_memory_bytes
          type: gauge
        - name: process_start_time_seconds
          type: gauge
        - name: process_cpu_seconds_total
          type: counter
        - name: process_open_fds
          type: gauge
        - name: process_max_fds
          type: gauge
