id: hawkular-openshift-agent
kind: Template
apiVersion: v1
name: Hawkular OpenShift Agent Template
metadata:
  name: hawkular-openshift-agent
  metrics-infra: agent
parameters:
- description: The version of the image to use
  name: IMAGE_VERSION
  value: latest
objects:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: hawkular-openshift-agent
    labels:
      metrics-infra: agent
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - namespaces
    - nodes
    - pods
    - projects
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: hawkular-openshift-agent
    labels:
      metrics-infra: agent
- apiVersion: v1
  kind: Secret
  metadata:
    name: hawkular-openshift-agent-status
    labels:
      metrics-infra: agent
  data:
    username: ZGV2
    password: Y2hhbmdlbWU=
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: hawkular-openshift-agent
    labels:
      name: hawkular-openshift-agent
      metrics-infra: agent
  spec:
    selector:
      matchLabels:
        name: hawkular-openshift-agent
    template:
      metadata:
        labels:
          name: hawkular-openshift-agent
          metrics-infra: agent
      spec:
        serviceAccount: hawkular-openshift-agent
        containers:
        - image: hawkular/hawkular-openshift-agent:${IMAGE_VERSION}
          name: hawkular-openshift-agent
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          command:
            - "/opt/hawkular/hawkular-openshift-agent"
            - "-config"
            - "/hawkular-openshift-agent-configuration/config.yaml"
            - "-v"
            - "4"
          env:
          - name: K8S_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: EMITTER_STATUS_CREDENTIALS_USERNAME
            valueFrom:
              secretKeyRef:
                name: hawkular-openshift-agent-status
                key: username
          - name: EMITTER_STATUS_CREDENTIALS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hawkular-openshift-agent-status
                key: password
          volumeMounts:
          - name: hawkular-openshift-agent-configuration
            mountPath: "/hawkular-openshift-agent-configuration"
        volumes:
        - name: hawkular-openshift-agent-configuration
          configMap:
            name: hawkular-openshift-agent-configuration
        - name: hawkular-openshift-agent
          configMap:
            name: hawkular-openshift-agent-configuration
