id: hawkular-openshift-agent
kind: Template
apiVersion: v1
name: Hawkular OpenShift Agent Template
metadata:
  name: hawkular-openshift-agent
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: hawkular-agent
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: hawkular-openshift-agent
    labels:
      name: hawkular-openshift-agent
  spec:
    selector:
      name: hawkular-openshift-agent
    replicas: 1
    template:
      version: v1
      metadata:
        labels:
          name: hawkular-openshift-agent
      spec:
        serviceAccount: hawkular-agent
        containers:
        - image: hawkular/hawkular-openshift-agent:latest
          imagePullPolicy: Never
          name: hawkular-openshift-agent
          command:
            - "/opt/hawkular/hawkular-openshift-agent"
            - "-config"
            - "/hawkular-openshift-agent-configuration/config.yaml"
            - "-v"
            - "4"
          env:
          - name: K8S_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: HAWKULAR_SERVER_URL
            value: https://hawkular-metrics
          - name: HAWKULAR_SERVER_CA_CERT_FILE
            value: "/hawkular-metrics-certificate/hawkular-metrics-ca.certificate"
          - name: HAWKULAR_SERVER_USERNAME
            valueFrom:
              secretKeyRef:
                name: hawkular-metrics-account 
                key: hawkular-metrics.username
          - name: HAWKULAR_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hawkular-metrics-account
                key: hawkular-metrics.password
          volumeMounts:
          - name: hawkular-metrics-certificate
            mountPath: "/hawkular-metrics-certificate"
          - name: hawkular-openshift-agent-configuration
            mountPath: "/hawkular-openshift-agent-configuration"
        volumes:
        - name: hawkular-metrics-certificate
          secret:
            secretName: hawkular-metrics-certificate
        - name: hawkular-openshift-agent-configuration
          configMap:
            name: hawkular-openshift-agent-configuration
